apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    environment: prod
  name: prod-database
  namespace: default
spec:
  backup:
    barmanObjectStore:
      data:
        compression: gzip
      destinationPath: s3://cnpg-backups/default/prod-database
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: backup-s3-creds
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: backup-s3-creds
      wal:
        compression: gzip
    retentionPolicy: 7d
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  instances: 1
  postgresql:
    parameters:
      max_connections: '200'
      shared_buffers: 256MB
  storage:
    size: 10Gi
